#!/usr/bin/env php
<?php
/**
 * Yii command line script for Unix/Linux.
 *
 * This is the bootstrap script for running yiic on Unix/Linux.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @link http://www.yiiframework.com/
 * @copyright Copyright &copy; 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

$curpath = realpath(dirname(__FILE__));
if (!file_exists($curpath.'/yiic.php')) {
  $curpath = realpath($curpath.'/../grundik/yii-migrate/');
}
require_once(dirname(__FILE__).'/yiic.php');
